service: probot-invite-koa

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10

functions:

  probot:
    handler: index.handler

    environment:
      WEBHOOK_SECRET: development
      APP_ID: 10789
      LOG_FORMAT: json
      WEBHOOK_PROXY_URL: https://smee.io/YWDuVjj2fWHz7Vlp

    events:
      - http:
         path: /probot
         method: get

      - http:
         path: /probot
         method: post

  app:
    handler: app.handler

    environment:
      WEBHOOK_SECRET: development
      APP_ID: 10789
      LOG_FORMAT: json
      WEBHOOK_PROXY_URL: https://smee.io/YWDuVjj2fWHz7Vlp
      SESSION_TOKEN: 26ff4488fa74ee300932d8d7b90c6e6bd9147d39

    events:
      - http:
         path: /hello
         method: get

      - http:
         path: /good-bye
         method: get
