service: probot-invite-koa

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10

functions:

  probot:
    handler: index.handler

    environment:
      WEBHOOK_SECRET: development
      APP_ID: <APP_ID>
      LOG_FORMAT: json

    events:
      - http:
         path: /probot
         method: get

      - http:
         path: /probot
         method: post

  app:
    handler: app.handler

    environment:
      WEBHOOK_SECRET: development
      APP_ID: <APP_ID>
      LOG_FORMAT: json

    events:
      - http:
         path: /hello
         method: get

      - http:
         path: /good-bye
         method: get
